require('config.settings')
require('config.packer')
require('config.mappings')

require('config.lsp.config')
require('config.cmp')
require('config.treesitter')
require('config.colors.material')
require('config.gitsigns')
require('config.nvim-tree')
require('config.lualine')
require('config.bufferline')
require('config.dashboard')
require('config.autopairs')
require('config.tmux')
require('config.toggleterm')
