require('config.settings')
require('config.packer')
require('config.mappings')

require('config.lsp.language-servers')
require('config.cmp')
require('config.treesitter')

require('config.colors.github')
require('config.gitsigns')
require('config.nvim-tree')
require('config.notify')
require('config.lualine')
require('config.shade')
require('config.bufferline')
